# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
np.__version__

'1.26.3'

In [6]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2628220032720
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.3
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.7
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:

#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
null_vector = np.zeros(10)
null_vector.size,null_vector

(10, array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

#### 4. How to find the memory size of any array (★☆☆)

In [14]:
null_vector.nbytes,null_vector.itemsize*null_vector.size

(80, 80)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [19]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [24]:
new_vector = np.zeros(10)
new_vector[4]=1
new_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [27]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [38]:
vector= np.arange(10,20)
vector[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [40]:
matrix = np.reshape(np.arange(0,9),[3,3])
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [50]:
vector = np.nonzero([1,2,0,0,4,0])
vector[0]

array([0, 1, 4], dtype=int64)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [3]:
matrix = np.eye(3,3)
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [6]:
array = np.random.randint(1,10,size=(3,3,3))
array

array([[[8, 3, 8],
        [8, 9, 7],
        [6, 4, 9]],

       [[9, 3, 2],
        [9, 2, 5],
        [6, 1, 8]],

       [[9, 5, 1],
        [6, 4, 6],
        [9, 4, 5]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [7]:
array = np.random.randint(1,10,size=(10,10))
array,array.max(),array.min()

(array([[3, 3, 6, 7, 5, 2, 4, 6, 1, 3],
        [5, 6, 6, 4, 1, 8, 5, 6, 6, 3],
        [6, 3, 5, 5, 5, 5, 5, 6, 2, 6],
        [1, 4, 1, 5, 8, 5, 4, 2, 3, 1],
        [2, 7, 9, 5, 9, 4, 5, 5, 6, 1],
        [3, 5, 6, 7, 5, 4, 8, 6, 6, 4],
        [4, 9, 9, 2, 4, 1, 6, 7, 9, 9],
        [1, 8, 1, 1, 8, 7, 1, 4, 4, 7],
        [3, 4, 5, 1, 8, 2, 5, 7, 5, 5],
        [6, 5, 4, 3, 7, 3, 2, 6, 5, 4]]),
 9,
 1)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [9]:
array = np.random.randint(1,30,size=30)
array.mean()

13.033333333333333

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
array = np.ones((10,10))
array[1:-1,1:-1]=0
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [41]:
array = np.random.randint(1,10,size=(10,10))
array[:,[0,-1]] = 0
array[[0,-1],:] = 0
array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 6, 4, 7, 7, 6, 6, 9, 4, 0],
       [0, 7, 9, 4, 4, 1, 4, 3, 8, 0],
       [0, 2, 4, 5, 3, 5, 7, 5, 3, 0],
       [0, 5, 1, 9, 1, 5, 3, 2, 3, 0],
       [0, 9, 1, 7, 2, 8, 2, 2, 7, 0],
       [0, 1, 3, 9, 3, 4, 4, 1, 9, 0],
       [0, 3, 3, 9, 6, 4, 5, 1, 8, 0],
       [0, 6, 1, 4, 1, 8, 6, 5, 6, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [61]:
array = np.random.randint(1,10,size=(10,10))
array = np.pad(array, pad_width=1, constant_values=0)
array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 7, 3, 1, 4, 5, 1, 6, 5, 2, 8, 0],
       [0, 9, 1, 4, 1, 2, 8, 7, 6, 6, 6, 0],
       [0, 8, 4, 3, 4, 8, 6, 3, 7, 8, 4, 0],
       [0, 8, 8, 3, 9, 7, 7, 8, 6, 1, 5, 0],
       [0, 9, 4, 5, 9, 1, 5, 8, 4, 5, 9, 0],
       [0, 5, 1, 6, 8, 9, 3, 2, 3, 2, 5, 0],
       [0, 8, 3, 7, 7, 1, 2, 8, 1, 1, 3, 0],
       [0, 3, 1, 4, 1, 2, 3, 2, 5, 6, 3, 0],
       [0, 8, 2, 4, 9, 7, 7, 1, 3, 7, 2, 0],
       [0, 3, 6, 3, 8, 7, 3, 6, 4, 8, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [47]:
0*np.nan, np.nan == np.nan, np.inf > np.nan, np.nan-np.nan, np.nan in set([np.nan]), 0.3 == 3*0.1

(nan, False, False, nan, True, False)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [56]:
matrix = np.zeros(shape=(5,5))
matrix = np.diag([1,2,3,4],k=-1)
matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [75]:
matrix = np.zeros(shape=(8,8))
matrix[1::2,::2]=1
matrix[::2,1::2]=1
matrix

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [76]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [14]:
np.tile([[0,1],[1,0]],(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [16]:
matrix = np.random.randint(1,5,(5,5))
matrix = (matrix - np.mean(matrix))/(np.std(matrix))
matrix

array([[ 1.37281295,  0.55566238, -1.07863874, -0.26148818, -1.07863874],
       [-1.07863874,  1.37281295,  1.37281295, -1.07863874, -0.26148818],
       [-1.07863874, -1.07863874, -1.07863874, -1.07863874,  0.55566238],
       [-1.07863874,  0.55566238,  0.55566238,  0.55566238,  1.37281295],
       [-0.26148818,  1.37281295, -1.07863874,  1.37281295,  0.55566238]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [17]:
color = np.dtype([('r',np.ubyte),
                  ('g',np.ubyte),
                  ('b',np.ubyte),
                  ('a',np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
mat1 = np.random.randint(1,3,(5,3))
mat2 = np.random.randint(1,3,(3,2))
mat3 = np.dot(mat1,mat2)
mat3

array([[6, 6],
       [4, 4],
       [7, 7],
       [4, 4],
       [5, 5]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [40]:
array = np.arange(10)
array[(3<array) & (array<8)] *= -1
array

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [42]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [52]:
Z = np.arange(10)
Z**Z, 2 << Z >> 2 ,Z < -Z, 1j*Z, Z/1/1, #Z<Z>Z

(array([        1,         1,         4,        27,       256,      3125,
            46656,    823543,  16777216, 387420489]),
 array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256], dtype=int32),
 array([False, False, False, False, False, False, False, False, False,
        False]),
 array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
        0.+8.j, 0.+9.j]),
 array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [55]:
np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float)

C:\Users\rohit\AppData\Local\Temp\ipykernel_8744\2446836393.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float)
C:\Users\rohit\AppData\Local\Temp\ipykernel_8744\2446836393.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float)
C:\Users\rohit\AppData\Local\Temp\ipykernel_8744\2446836393.py:1: RuntimeWarning: invalid value encountered in cast
  np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float)


(nan, 0, array([-2.14748365e+09]))

#### 29. How to round away from zero a float array ? (★☆☆)

In [65]:
array = np.random.random(5)
np.ceil(array), array, np.copysign(np.ceil(np.abs(array)), array)

(array([1., 1., 1., 1., 1.]),
 array([0.25588178, 0.41808923, 0.13088509, 0.56768658, 0.88762948]),
 array([1., 1., 1., 1., 1.]))

#### 30. How to find common values between two arrays? (★☆☆)

In [71]:
a1 = np.random.randint(1,5,(5))
a2 = np.random.randint(1,5,(5))
np.intersect1d(a1,a2),a1,a2

(array([1, 2, 3]), array([4, 2, 1, 4, 3]), array([3, 1, 3, 2, 3]))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

AttributeError: 'int' object has no attribute 'IGNORE'

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [3]:
np.sqrt(-1),np.emath.sqrt(-1)

C:\Users\rohit\AppData\Local\Temp\ipykernel_7308\4288405921.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1),np.emath.sqrt(-1)


(nan, 1j)

In [2]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\rohit\AppData\Local\Temp\ipykernel_7308\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [13]:
date_today = np.datetime64('today','D')
date_yest = date_today - np.timedelta64(1,'D')
date_tomm = date_today + np.timedelta64(1,'D')
date_yest,date_today,date_tomm

(numpy.datetime64('2024-05-21'),
 numpy.datetime64('2024-05-22'),
 numpy.datetime64('2024-05-23'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [17]:
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

dates_jul = np.arange(start_date,end_date,dtype='datetime64[D]')
dates_jul

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [18]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
A

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [19]:
array = np.random.uniform(0,10,10)
array - array%1, array//1, np.floor(array), array.astype(int), np.trunc(array)

(array([0., 5., 4., 0., 6., 6., 6., 9., 7., 4.]),
 array([0., 5., 4., 0., 6., 6., 6., 9., 7., 4.]),
 array([0., 5., 4., 0., 6., 6., 6., 9., 7., 4.]),
 array([0, 5, 4, 0, 6, 6, 6, 9, 7, 4]),
 array([0., 5., 4., 0., 6., 6., 6., 9., 7., 4.]))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [33]:
array = np.ones((5,5))
array *= np.arange(5)
array

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [34]:
array = np.zeros((5,5))
array += np.arange(5)
array

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [31]:
def generator():
    for i in range(1,11):
        yield i

array = np.fromiter(generator(),dtype=float)
array

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [27]:
array = np.linspace(0,1,11,endpoint=False)[1:]
array

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [22]:
array = np.random.random(10)
array.sort()
array

array([0.10136341, 0.17204788, 0.23609226, 0.24587291, 0.32982971,
       0.47457273, 0.68731681, 0.79354014, 0.85211922, 0.86056282])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [3]:
array = np.array([1, 2, 3, 4, 5])
sum(array)

15

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [10]:
A = np.random.randint(1,5,(1,4))
B = np.random.randint(1,5,(1,4))
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [11]:
immutable_array = np.array([1,2,3,4,5])
immutable_array.flags.writeable = False
try:
    immutable_array[0] = 10
except Exception as e:
    print(e)

assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [13]:
cartesian_coords = np.random.randint(1,10,(10,2))
X,Y = cartesian_coords[:,0],cartesian_coords[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
R,T

(array([ 8.60232527, 12.72792206,  3.60555128,  9.48683298, 10.81665383,
         9.21954446,  6.32455532,  8.54400375,  7.28010989,  8.06225775]),
 array([0.95054684, 0.78539816, 0.5880026 , 1.24904577, 0.5880026 ,
        0.86217005, 0.32175055, 1.21202566, 0.27829966, 1.44644133]))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [31]:
vector = np.random.random(10)
vector[vector.argmax()] = 0
vector

array([0.43627362, 0.36387229, 0.33712007, 0.68352596, 0.        ,
       0.46478373, 0.2624023 , 0.20774756, 0.11132481, 0.71113069])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [36]:
matrix = np.zeros((5,5), [('x',float),('y',float)])
matrix['x'],matrix['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
matrix

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [43]:
X = np.array([1,2,3,4,5,6,7,8])
y = X+0.5
X = X[:,np.newaxis]
Y = Y[np.newaxis,:]
C = 1.0 / (X-y)
C

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [44]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [45]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [51]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

39


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)